forcedotcom/SalesforceMobileSDK-Shared

libs/smartsync.js
test/MockSmartSyncPlugin.js
test/SFSmartSyncTestSuite.js

The mock smartsync plugin uses a smartsync.js SObjectCollection to do a sync down.
So I enhanced SObjectCollection to support a new option: merge mode (from the "enum" Force.MERGE_MODE_DOWNLOAD.
I also added a new test that does a sync down with merge mode leave-if-changed.

Hybrid changes for sync down without overwrite of dirty records

---

dependencies/ratchet2/ratchet.modified.css
samples/accounteditor/css/ratchet.css
samples/simplesync/css/ratchet.css
samples/simplesyncreact/css/ratchet.css
samples/userlist/css/ratchet.css

Manually patched ratchet.css (with suggestion from https://github.com/twbs/ratchet/issues/724)
Pointing to ratchet.modified.css (so that running tools/update.sh won't revert the change)
It's really a one line fix:
272c272
-webkit-transform: translateZ(1);
replacing
-webkit-transform: translateZ(0);

iOS 8 ratchet fix

---

libs/smartsync.js

When a lookup field is null and a field on the object was being queried for, there was a crash happening. Added check to make sure the lookup field is not null before querying for the related field

Fix to prevent a crash when a lookup field is null

---

libs/react.force.net.js

Too late for 4.0.2, but I will have the sample app point to this commit

Both iOS and Android bridges expect params as object not string

---

node/test_force.js

Switching to building the app scheme directly, after the updates to support shared schemes for the iOS template apps.

Changing test script to build iOS app scheme

---

node/cordovaHelper.js

The latest version of shelljs does not use the output(deprecated in 0.6 and removed in 0.7) property of exec any more. It has been replaced by stdout.
https://github.com/shelljs/shelljs/wiki/Migrating-from-v0.6-to-v0.7
https://github.com/shelljs/shelljs/wiki/Migrating-from-v0.5.3-to-v0.6

Use stdout instead of output

---

node/postpublish.js
node/prepublish.js

```npm``` uses any file starting with ```README``` as the readme for the package. Hence, renaming the original file to ```README.md.orig``` wasn't working. This changes it to ```ORIGINAL.md``` now, so that there's only one ```README.md```.

Fixing bug with npm readme

---

libs/react.force.smartstore.js

Same APIs that we added for ```Cordova```.

Adding React support for external soup storage

---

test/SFSmartStoreTestSuite.js

Android didn't fail because smartstore plugin operations are serialized

That was the cause for the 2 alter soup with spec test failures on iOS

---

samples/accounteditor/AccountEditor.html

Emulator starts offline (navigator.onLine is false). And trying to go online was not working.
EditAccountPage was throwing an error when one tried to go online.
EditAccountPage is always watching the app.offlineTracker and before the fix tried to access its model when a toggle takes place.
And it was failing if the model was undefined.
Now it won't fail if it doesn't have a model.
NB:It would be better for it to start/stop watching the app.offlineTracker as it comes into view/leaves view but that change is more involved.
Also sync screen won't be shown if there is nothing to sync.

Bug fix for account editor on Android

---

node/cordovaHelper.js

line breaks are Carriage Return (CR, \r, on older Macs), Line Feed (LF, \n, on Unices incl. Linux) or CR followed by LF (\r\n, on WinDOS). We need to take care to replace /r/n for Windows

handle the line end for Windows platform

---

libs/smartsync.js
test/MockSDKInfo.js
test/SFSDKInfoTestSuite.js
test/test.html

* SDK info test was failing because in the browser cordova.platformId is neither ios nor android
* Smart sync tests were failing because forcetk was not initialized with useXhrNetworking

Fixing tests that were not passing in browser

---

test/SFSmartSyncTestSuite.js

Test was fetching records by with name like fixedPrefix% and therefore could end up picking up records created by other (unfinished or concurrent) runs of the test
Now we are using a unique prefix for every run.

Fix for testFetchApexRestObjectsFromServer

---

libs/forcetk.mobilesdk.js
libs/smartsync.js
test/SFForcetkTestSuite.js

Native code was expecting them in the payload
NB: we had to make the same change in react.force.net.js (https://github.com/forcedotcom/SalesforceMobileSDK-Shared/commit/6155572260b3c45e6d6bd369472331793531166c)

Query string lost for GETs with network plugin

---

test/SFSmartSyncTestSuite.js

The sync has a soup name but the target doesn't get a handle on the sync when running (maybe we could change that)

Refresh sync target needs soup name

---

gen/cordova_plugins.js
gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.client.js
gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.js
gen/plugins/com.salesforce/com.salesforce.util.promiser.js
gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.client.js
gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.js
gen/plugins_with_define/com.salesforce/com.salesforce.util.promiser.js
libs/cordova.force.js
libs/force.js
libs/smartsync.js
samples/userlist/css/ratchet-theme-android.css
samples/userlist/css/ratchet-theme-android.min.css
samples/userlist/css/ratchet-theme-ios.css
samples/userlist/css/ratchet-theme-ios.min.css
samples/userlist/css/ratchet.min.css
samples/userlist/index.html
samples/userlist/js/jquery.js
test/MockSmartStore.js
test/SFAbstractSmartStoreTestSuite.js
test/SFSDKInfoTestSuite.js
test/SFSmartStoreLoadTestSuite.js
test/SFSmartStoreTestSuite.js
test/SFSmartSyncTestSuite.js
test/SFTestSuite.js
test/forcepluginstest/index.html
test/test.html

* smartsync.js no longer depends on jquery - instead it uses native promises 
* tests no longer use jquery
* userlist sample app no longer uses jquery however sample apps that use Backbone.View still need jquery
* there is now a smartstoreClient (navigator.smartstoreClient or cordova.require("com.salesforce.plugin.smartstore.client") which offers promise-based versions of smartstore methods. (Previously we had such an object in smartsync.js, and we were using it in tests).
* there is now a forceJsClient (defined in force.js) which offers promise-based versions of force's async methods. (Previously we had such an object in smartsync.js, and we were using it in tests).
* NB: Native promises are supported on iOS and on Android 20 (4.4.4) and above.
Currently, our min Android version is 19 …

Move to native promises / promise-based smartstore and force clients

---

node/test_force.js

test_force.js invokes forceios which internally does a pod install (which goes against the published pod specs).
Then test_force.js edit the pod file of the generated application to point to local copies of the Mobile SDK and then does a pod update.
That doesn't work now because the SalesforceAnalytics pod exists in development but not in production.
The solution is to have test_force.js disable the pod install call in forceios (actually it lives in createApp.sh) before executing forceios.

test_force fails to create ios native apps

---

libs/cordova.force.js

Use the passed method parameter instead of undefined variable for push notification error handler

change from undefined to defined variable for push notification handler

---

gen/plugins/com.salesforce/com.salesforce.plugin.network.js
gen/plugins_with_define/com.salesforce/com.salesforce.plugin.network.js
libs/cordova.force.js
libs/force.js

New flag `returnResponseAsBlob` (default false) in network plugin `sendRequest` method and force.js `request()` method - when true expects a JavaScript Blob back.
* Updated the network plugin
The native side of the network plugin will send back the base64 encoded body and the content type and the javascript side of the network plugin takes care of decoding the body and building a JavaScript blob from it.
* Updated force.js also - it also works when running in a browser. There was a `getAttachment()` method in force.js already but it was broken.
Example
```javascript
force.getAttachment("--valid-attachment-id--",
function(blob) {
document.getElementById("--id-of-some-img-tag").src = URL.createObjectURL(blob);
},
function(error) {
alert("error->[" + error + "]");
}
);
```
Note: Will send a …

Binary download support

---

libs/cordova.force.js
libs/force.js

Blob is not an option on react native, so to be consistent, giving base64 back to the app here also.
Renamed returnResponseAsBlob to returnBinary.

Giving base64 back to the app

---

libs/force.js

Since v37, upsert with external id null is allowed - it does a create (but post must be used).
We made the change on the native side last year.

Upsert with null external id

---

test/SFSDKInfoTestSuite.js

SDK info test failing because we renaming smartsync to mobilesync but did not update order of expected plugins in test.

Plugins are in alphabetic order

---

gen/plugins/com.salesforce/com.salesforce.util.exec.js
gen/plugins_with_define/com.salesforce/com.salesforce.util.exec.js
libs/cordova.force.js

Gus Bug: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000077azDIAQ/view
In cordova.js, there is a function called exec as part of com.salesforce.util.exec JS module. That function is used for async smartstore operations and is using console.time() and console.timeEnd() to log the time of a given operation.
The key given as identifier is var tag = "TIMING " + service + ":" + action;
The issue is that the key is not unique and when concurrent operations are executed, the console.time() calls will conflict with each other. For example, if we execute a smartstore pgRunSmartQuery operation, the key will be TIMING com.salesforce.smartstore:pgRunSmartQuery. I observed cases where a short operation (say A) was followed by a longer operation (say B) in parallel. In that case, B …

Make perf marker tag unique to fix the case when there two overlapping operations of the same type

---

libs/force.js

parseUrl("https://asdasd:123/abc/de?a=b&c=d")
=> {hash: "", host: "asdasd:123", hostname: "asdasd", params: {a: "b", c: "d"}, path: "/abc/de", port: "123", protocol: "https:"}
parseUrl("/abc/de?a=b&c=d")
=> {hash: "", host: "", hostname: "", params: {a: "b", c: "d"}, path: "/abc/de", port: "", protocol: ""}

parseUrl can now handle full url or relative ones

---

libs/force.js

Alternatively, I could have changed the test.

Tweaking parseUrl to behave like the old implementation

---

test/SFSmartStoreTestSuite.js

So this test is no longer valid - there won't be an error at query parsing time.

In 9.1, it's possible to select or filter by non-indexed fields

---

test/SFMobileSyncTestSuite.js

Since syncs run on a parallel thread to the JS runtime, sometimes the sync operation can make progress before the assertion which checks for 0% progress.  Since there are other native tests which check the sync operations' behavior, the assertions here can be relaxed a bit to ensure tests pass.

Fixes flaky tests in trySync* methods
