- samples/notesync/NoteSync.html
- samples/notesync/bootconfig.json
- samples/notesync/css/ratchet-theme-ios.css
- samples/notesync/css/ratchet.css
- samples/notesync/css/styles.css
- samples/notesync/js/MockCordova.js
- samples/notesync/js/MockSmartStore.js
- samples/notesync/js/MockSmartSyncPlugin.js
- samples/notesync/js/auth.js
- samples/notesync/js/backbone-min.js
- samples/notesync/js/backbone.js
- samples/notesync/js/cordova.force.js
- samples/notesync/js/fastclick.js
- samples/notesync/js/forcetk.mobilesdk.js
- samples/notesync/js/forcetk.ui.js
- samples/notesync/js/jquery.min.js
- samples/notesync/js/smartsync.js
- samples/notesync/js/stackrouter.js
- samples/notesync/js/underscore-min.js
For now pulling to a new branch called notesync - we can decide later what to do with it
> New hybrid sample app doing smartsync with notes

- samples/notesync/NoteSync.html
- samples/notesync/bootconfig.json
- samples/notesync/css/ratchet-theme-ios.css
- samples/notesync/css/ratchet.css
- samples/notesync/css/styles.css
- samples/notesync/js/MockCordova.js
- samples/notesync/js/MockSmartStore.js
- samples/notesync/js/MockSmartSyncPlugin.js
- samples/notesync/js/auth.js
- samples/notesync/js/backbone-min.js
- samples/notesync/js/backbone.js
- samples/notesync/js/cordova.force.js
- samples/notesync/js/fastclick.js
- samples/notesync/js/forcetk.mobilesdk.js
- samples/notesync/js/forcetk.ui.js
- samples/notesync/js/jquery.min.js
- samples/notesync/js/smartsync.js
- samples/notesync/js/stackrouter.js
- samples/notesync/js/underscore-min.js
Will remove mobile2.t client id key once we have a sandbox org with content notes enabled
> NoteSync hybrid sample app

- gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins/com.salesforce/com.salesforce.plugin.smartsync.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartsync.js
- libs/cordova.force.js
- test/MockSmartStore.js
- test/MockSmartSyncPlugin.js
- test/SFSmartStoreTestSuite.js
- test/SFSmartSyncTestSuite.js
Added support for global store in smartsync plugin and mock smartsync plugin
Added test for global store and Force.StoreCache
TODO: tests for global store with syncDown/syncUp/etc
> Global store and smartsync plugin 

- test/MockSmartSyncPlugin.js
- test/SFSmartSyncTestSuite.js
Fixed issues in mock smartsync plugin revealed by new tests
> Added tests for sync down / sync up using global store soup

- gen/plugins/com.salesforce/com.salesforce.plugin.oauth.js
- gen/plugins/com.salesforce/com.salesforce.plugin.sdkinfo.js
- gen/plugins/com.salesforce/com.salesforce.plugin.sfaccountmanager.js
- gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins/com.salesforce/com.salesforce.plugin.smartsync.js
- gen/plugins/com.salesforce/com.salesforce.util.bootstrap.js
- gen/plugins/com.salesforce/com.salesforce.util.event.js
- gen/plugins/com.salesforce/com.salesforce.util.exec.js
- gen/plugins/com.salesforce/com.salesforce.util.logger.js
- gen/plugins/com.salesforce/com.salesforce.util.push.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.oauth.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.sdkinfo.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.sfaccountmanager.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartsync.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.bootstrap.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.event.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.exec.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.logger.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.push.js
- libs/cordova.force.js
- samples/simplesync/SimpleSync.html
- test/MockSmartStore.js
- test/SFSmartStoreTestSuite.js
- orderPath enhancement
- match (full-text search) query
- new tests (but more needed)
> Full-text search - (some of the) hybrid work

- test/SFSmartStoreTestSuite.js
Mock could handle it / but not sqlcipher ;-)
> Removing unsupported query

- libs/smartsync.js
Keeping the API consistent to have getMore method in all responses.
> fixing collection result on mru query to include getMore method

- libs/forcetk.mobilesdk.js
Need to handle special protocol scheme for windows containers.
> adding ms-appx and ms-appx-web

- libs/react.force.net.js
- libs/react.force.oauth.js
- libs/react.force.smartstore.js
- libs/react.force.smartsync.js
They were previously in the iOS repo, but they will be shared between iOS and Android.
Next the PR for the iOS repo to get them from the shared submodule.
> Moving react js modules to shared repo

- libs/react.force.net.js
iOS and Android changes needed to consume the new endPoint parameter
Also fixed queryMore
> Change to allow net bridge to call api that are not under /services/data

- gen/plugins/com.salesforce/com.salesforce.util.push.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.push.js
- libs/cordova.force.js
Originally from [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/141).
> Fix for console.error

- test/MockSDKInfo.js
- test/MockSmartStore.js
- test/SFSmartStoreTestSuite.js
Also testing queries that go against a non-leaf node (array nodes are just one example)
When I run those tests from iOS/Android, changes might be required
> Path through array in MockSmartStore.js

- libs/react.force.net.js
A fix for https://github.com/forcedotcom/SmartSyncExplorerReactNative/issues/31
> Not packing query params / method in the path

- gen/plugins/com.salesforce/com.salesforce.plugin.oauth.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.oauth.js
- libs/cordova.force.js
- libs/react.force.oauth.js
The android support for it is coming next
> authenticate() method in oauth react bridge

- libs/cordova.force.js
plugin.xml showed new phonegap-plugin-push as dependency but this
module was not updated
> code updated for phonegap-plugin-push

- gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.js
- libs/cordova.force.js
- test/MockSmartStore.js
- test/SFSmartStoreTestSuite.js
Modified mock smartstore
Added test
> Support for remove from soup by query

- gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.js
- libs/cordova.force.js
- test/MockSmartStore.js
- test/SFSmartStoreTestSuite.js
changed smartstore plugin js
changed mock smartstore
changed existing query tests to also test with select paths parameter
> Hybrid changes for select paths in query spec

- node/test_force.js
Also calling install.sh (the android repo now does npm install in its install.sh, see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1164)
> Fixing bug introduced by switch to miscUtils.replaceTextInFile

- gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.js
- libs/cordova.force.js
- samples/smartstoreexplorer/index.html
- samples/smartstoreexplorer/smartstoreexplorer.js
Added new features to smartstoreexplorer app to test new soup spec feature
> Added SoupSpec and methods for registerSoupWithSpec and getSoupSpec

- test/SFSmartStoreTestSuite.js
Now testing external to internal in addition to internal to external
> Alter soup with spec tests enhanced

- test/SFSDKInfoTestSuite.js
> fix getInfo test

- gen/cordova_plugins.js
- gen/plugins/com.salesforce/com.salesforce.plugin.network.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.network.js
- libs/cordova.force.js
- libs/forcetk.mobilesdk.js
- test/SFSDKInfoTestSuite.js
`forcetk` changes coming up next. Do not merge until then.
> Adding new network plugin

- test/MockSmartSyncPlugin.js
testCleanResyncGhosts now works in browser
> Mock implementation for cleanResyncGhosts

- test/MockSmartSyncPlugin.js
- test/SFSmartSyncTestSuite.js
To be consistent with mru sync down
> Using sobjectType instead of objectType in refresh sync down 

- libs/force.js
This is the unmodified force.js copied from https://github.com/ccoenraets/forcejs/blob/a9348b90a046e12aac9b56864359c24e5b246abe/force.js
In an upcoming PR, I'll make changes to it (to work with the network plugin) and will change sample / template / test apps to use it instead of forcetk.
I wanted the upcoming PR diff to show the changes I made to force.js (instead of just showing it as all new).
> force.js library

- gen/plugins/com.salesforce/com.salesforce.plugin.network.js
- gen/plugins/com.salesforce/com.salesforce.plugin.oauth.js
- gen/plugins/com.salesforce/com.salesforce.plugin.sfaccountmanager.js
- gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.client.js
- gen/plugins/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins/com.salesforce/com.salesforce.plugin.smartsync.js
- gen/plugins/com.salesforce/com.salesforce.util.bootstrap.js
- gen/plugins/com.salesforce/com.salesforce.util.event.js
- gen/plugins/com.salesforce/com.salesforce.util.exec.js
- gen/plugins/com.salesforce/com.salesforce.util.logger.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.network.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.oauth.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.sfaccountmanager.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.client.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartstore.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartsync.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.bootstrap.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.event.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.exec.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.logger.js
- libs/cordova.force.js
- libs/react.force.smartstore.js
- libs/smartsync.js
- test/MockSmartStore.js
- test/MockSmartSyncPlugin.js
- test/SFSmartStoreTestSuite.js
- test/SFSmartSyncTestSuite.js
Changes related to the ability to specify StoreName in JS smartstore/smartsync apis. Added new Store related API(s).
> Specify the target store name to achieve a soup per store

- package.json
That way the code can be pulled into hybrid templates using npm.
> Package.json for shared repo

- dependencies/promise-polyfill/promise.js
- test/forcepluginstest/index.html
- tools/bower.json
Native promises are only available starting with android 20, so using a polyfill
> Fixing hybrid tests for android 19

- test/SFSDKInfoTestSuite.js
This test failed consistently.
> update the version check in hybrid test accordingly

- samples/contactexplorer/inline.js
This code throws an error and `contacts` is [global](https://github.com/apache/cordova-plugin-contacts#cordova-plugin-contacts).
`var contactOptionsType = cordova.require("org.apache.cordova.contacts.ContactFindOptions");`
> Fix file explorer example

- libs/force.js
- libs/smartsync.js
- samples/contactexplorer/index.html
- samples/smartstoreexplorer/index.html
- test/SFForceJSTestSuite.js
NB: SOSL result looks different
> Move to API version 39 (already done on Android)

- samples/simplesyncreact/SimpleSync.html
- samples/smartsyncexplorer/SmartSyncExplorer.html
Browser promise do not have "done"
> Fixing SmartSyncExplorerHybrid (and SimpleSync)

- gen/plugins/com.salesforce/com.salesforce.plugin.smartsync.js
- gen/plugins/com.salesforce/com.salesforce.util.push.js
- gen/plugins_with_define/com.salesforce/com.salesforce.plugin.smartsync.js
- gen/plugins_with_define/com.salesforce/com.salesforce.util.push.js
- libs/cordova.force.js
- samples/smartsyncexplorer/SmartSyncExplorer.html
- test/MockSmartSyncPlugin.js
- test/SFSmartSyncTestSuite.js
* New methods in plugin: getSyncByName, deleteSyncById, deleteSyncByName
* (Optional) syncName argument in syncDown and syncUp
* Mock implementation (to be able to test in a browser)
* New tests
* Some misc refactoring of the code that keeps the plugin backwards compatible
> Names for sync

- test/SFSmartSyncTestSuite.js
Another flapper due to `SOLR search indexing`.
> Fixing failing test

- libs/force.js
- samples/contactexplorer/index.html
- samples/smartstoreexplorer/index.html
- test/SFForceJSTestSuite.js
We need this to send `BundleID` up.
> Upgrading to v42.0

- test/SFSmartSyncTestSuite.js
Goes with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2402
> cleanResyncGhosts now calls its callback upon completion

- test/SFSDKInfoTestSuite.js
Saw this failure from the test runs of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2479.
> Fixing Info plugin test, rev'ing version

- credshelper/README.md
- credshelper/index.html
- credshelper/oauthcallback.html
- credshelper/package.json
> Simple web app to produce the json for test_credentials.json

- credshelper/README.md
- credshelper/index.html
NB: to see the additional fields, you must run a browser with CORS policy disabled.
> Additional fields for test_credentials.json (for Android)

- samples/smartsyncexplorer/SmartSyncExplorer.html
Otherwise a field containing HTML breaks the app (e.g. <img src=x onerror="alert(1)"/>)
> Escaping html

- gen/cordova_plugins.js
- setversion.sh
- test/SFForceJSTestSuite.js
Also fixing setversion 
Dropping unused test code (that had version in it)
> Fixing version in cordova_plugins.js

- libs/force.js
- samples/contactexplorer/index.html
- samples/smartstoreexplorer/index.html
- test/SFForceJSTestSuite.js
v55.0 is partially rolled out in production. Will merge once it's on more instances.
> Moving to v55.0
